name: CI of mc_panda

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    # Run on Sunday, Tuesday and Thursday nights
    - cron: '0 23 * * 0,1,4'

jobs:

  clang-format:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install clang-format-6.0
      run: |
        sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt-get -qq update
        sudo apt-get -qq remove clang-6.0 libclang1-6.0 libclang-common-6.0-dev libllvm6.0
        sudo apt-get -qq install clang-format-6.0 clang-format
    - name: Run clang-format-check
      run: |
        ./.clang-format-check.sh
  build:
    needs: clang-format
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-latest]
        compiler: [gcc]
        build-type: [RelWithDebInfo]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install ROS dependencies
      if: startsWith(runner.os, 'Linux')
      run: |
        set -x
        set -e
        export ROS_DISTRO="melodic"
        sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
        wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
        sudo apt-get update -qq
        sudo apt-get install -qq ros-${ROS_DISTRO}-libfranka ros-${ROS_DISTRO}-franka-ros
        . /opt/ros/${ROS_DISTRO}/setup.bash
        echo "::set-env name=ROS_DISTRO::${ROS_DISTRO}"
        echo "::set-env name=PKG_CONFIG_PATH::${PKG_CONFIG_PATH}"
        echo "::set-env name=ROS_MASTER_URI::${ROS_MASTER_URI}"
        echo "::set-env name=ROS_PACKAGE_PATH::${ROS_PACKAGE_PATH}"
        echo "::set-env name=PYTHONPATH::${PYTHONPATH}"
        echo "::set-env name=CMAKE_PREFIX_PATH::${CMAKE_PREFIX_PATH}"
        echo "::set-env name=PATH::${PATH}"
        echo "::set-env name=LD_LIBRARY_PATH::${LD_LIBRARY_PATH}"
    - name: Install mc_rtc
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
        ubuntu: |
          apt: libmc-rtc-dev libcnoid-dev jvrc-choreonoid
          apt-mirrors:
            multi-contact:
              mirror: https://dl.bintray.com/gergondet/multi-contact-head
              key: 892EA6EE273707C6495A6FB6220D644C64666806
        macos: |
          cask: gfortran
          vcpkg:
            repo: jrl-umi3218/vcpkg
            user: ${{ github.actor }}
            token: ${{ github.token }}
          github:
            - path: frankaemika/libfranka
              ref: 0.8.0
    - name: Build and test
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
    - name: Slack Notification
      if: failure()
      uses: archive/github-actions-slack@master
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack-channel: '#ci'
        slack-text: >
          [mc_panda] Build *${{ matrix.os }}/${{ matrix.build-type }}* failed on ${{ github.ref }}
